# Generated by Django 4.2.1 on 2023-06-25 14:30

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='mainmenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menucode', models.IntegerField()),
                ('menuname', models.CharField(max_length=100)),
                ('menutype', models.IntegerField()),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('supervisor', 'Supervisor'), ('dataentry', 'Data Entry')], default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='MenuList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Menucode', models.IntegerField()),
                ('MenuType', models.IntegerField()),
                ('menuname', models.CharField(max_length=100)),
                ('submenuname', models.CharField(max_length=100)),
                ('menulink', models.CharField(max_length=100)),
                ('mainmenu', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.mainmenu')),
            ],
            managers=[
                ('menulist_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
